### ISSUE TITLE
大佬，能不能打包一下

### ISSUE THREAD

**Issue by jackw111** [mengbo/install#1]
大佬，能不能打包一下，[obsidian-custom-attachment-location],
你修改了代码，但是原作者好像并没有进行合并更新啊
你能不能打包一下发布，我们就能直接用了啊

**Comment by mengbo** [comment]
换 obsidian-attachment-management 吧，不要再纠结这个僵尸项目了。

**Comment by jackw111** [comment]
好吧，后面我fork了你的仓库，自己弄出了main.js文件，attachment-management 不能在我的手机上跑，
感谢大佬
